apps/clustercomposer/config/routes.rb
Rails.application.routes.draw do
  get 'azhpcclusters/index'
  get 'azhpcclusters/submit'
  get 'azhpcclusters/stop'
  get 'azhpcclusters/start'
  get 'azhpcclusters/delete'
  get 'azhpcclusters/destroy'
  get 'azhpcclusters/new_from_url'
  get 'azhpcclusters/copy'
  resources :templates, only: [:new, :create, :destroy]

  resources :workflows do
    member do
      put 'submit'
      put 'stop'
      post 'copy'
    end
  end

  post "create_default" => "azhpcclusters#create_default"
  get "new_from_path" => "azhpcclusters#new_from_path"
  post "create_from_path" => "azhpcclusters#create_from_path"
  root "azhpcclusters#index"

end

apps/clustercomposer/app/controllers/workflows_controller.rb
class WorkflowsController < ApplicationController
  before_action :update_jobs, only: [:index, :show, :destroy]

  # GET /workflows
  # GET /workflows.json
  def index
    if OODClusters.none?
      flash.now[:alert] = 'There are no configured hosts that allow you to submit jobs. Please contact your system administrator.'
    end

    @default_template = Template.default
    @templates = Template.all

    @selected_id = session[:selected_id]
    session[:selected_id] = nil
    @workflows = Workflow.preload(:jobs)
  end

  # GET /workflows/1
  # GET /workflows/1.json
  def show
    set_workflow
    @workflow = Workflow.find(params[:id])
    @workflow.jobs.last.update_status! unless @workflow.jobs.last.nil?
  end

  # GET /workflows/new
  def new
    @workflow = Workflow.new
    @templates = Template.all
  end

  def new_from_path
    @workflow = Workflow.new
    if params[:path]
      @workflow = Workflow.new_from_path(params[:path])
    end
  end

  # GET /workflows/1/edit
  def edit
    set_workflow
  end

  # POST /workflows
  # POST /workflows.json
  def create
    @templates = Template.all
    @workflow = Workflow.new(workflow_params)

    respond_to do |format|
      if @workflow.save
        session[:selected_id] = @workflow.id
        format.html { redirect_to workflows_url, notice: 'Cluster was successfully created.' }
        format.json { render :show, status: :created, location: @workflow }
      else
        format.html { render :new }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /create_default
  # POST /create_default.json
  def create_default
    @templates = Template.all
    @workflow = Workflow.new_from_template(Template.default)

    respond_to do |format|
      if @workflow.save
        format.html { redirect_to workflows_url, notice: 'Cluster was successfully created.' }
        format.json { render :show, status: :created, location: @workflow }
      else
        format.html { render :new }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /workflows/create_from_path
  # POST /workflows/create_from_path.json
  def create_from_path
    @workflow = Workflow.new_from_path(workflow_params[:staging_template_dir])
    @workflow.name = workflow_params[:name] unless workflow_params[:name].blank?
    @workflow.batch_host = workflow_params[:batch_host] unless workflow_params[:batch_host].blank?
    @workflow.script_name = workflow_params[:script_name] unless workflow_params[:script_name].blank?
    @workflow.account = workflow_params[:account] unless workflow_params[:account].blank?

    # validate path we are copying from. safe_path is a boolean, error contains the error string if false
    copy_safe, error = Filesystem.new.validate_path_is_copy_safe(@workflow.staging_template_dir.to_s)
    @workflow.errors.add(:staging_template_dir, error) unless copy_safe

    # If the workflow passes validation but a name hasn't been assigned, set the name to the inputted path
    if @workflow.errors.empty? && @workflow.name.blank?
      @workflow.name = @workflow.staging_template_dir
    end

    respond_to do |format|
      if @workflow.errors.empty? && @workflow.save
        format.html { redirect_to workflows_url, notice: 'Cluster was successfully created.' }
        format.json { render :show, status: :created, location: @workflow }
      else
        format.html { render :new_from_path }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workflows/1
  # PATCH/PUT /workflows/1.json
  def update
    set_workflow

    respond_to do |format|
      if @workflow.update(workflow_params)
        session[:selected_id] = @workflow.id
        format.html { redirect_to workflows_path, notice: 'Cluster was successfully updated.' }
        format.json { render :show, status: :ok, location: @workflow }
      else
        format.html { render :edit }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /workflows/1/stop
  def stop
    set_workflow

    @workflow.jobs.last.update_status! unless @workflow.jobs.last.nil?
    session[:selected_id] = @workflow.id

    respond_to do |format|
      if !@workflow.submitted?
        format.html { redirect_to workflows_url, alert: 'Cluster has not been submitted.' }
        format.json { head :no_content }
      elsif @workflow.stop
        format.html { redirect_to workflows_url, notice: 'Cluster was successfully stopped.' }
        format.js   { render :show }
        format.json { head :no_content }
      else
        @errors = @workflow.errors
        format.html { redirect_to workflows_url, alert: "Cluster failed to be stopped: #{@workflow.errors.to_a}" }
        format.json { render json: @workflow.errors, status: :internal_server_error }
      end
    end
  end

  # DELETE /workflows/1
  # DELETE /workflows/1.json
  def destroy
    set_workflow

    respond_to do |format|
      if @workflow.destroy
        format.html { redirect_to workflows_url, notice: 'Cluster was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to workflows_url, alert: "Cluster failed to be destroyed: #{@workflow.errors.to_a}" }
        format.json { render json: @workflow.errors, status: :internal_server_error }
      end
    end
  end

  # PUT /workflows/1/submit
  # PUT /workflows/1/submit.json
  def submit
    set_workflow

    # We want to allow the user to resubmit a job that has been run or failed. This will destroy all preexisting
    # job records for this workflow when the job is no longer queued or running, which will clear the submitted state.
    if @workflow.submitted? && !@workflow.active?
      @workflow.jobs.destroy_all
    end

    respond_to do |format|
      if @workflow.submitted?
        session[:selected_id] = @workflow.id
        format.html { redirect_to workflows_url, alert: 'Cluster has already been submitted.' }
        format.json { head :no_content }
      elsif @workflow.submit
        session[:selected_id] = @workflow.id
        format.html { redirect_to workflows_url, notice: 'Cluster was successfully submitted.' }
        format.json { head :no_content }
      else
        #FIXME: instead of alert with html, better to have alert and alert_error_output on flash
        format.html { redirect_to workflows_url, flash: { alert: 'Failed to submit batch job:', alert_error: @workflow.errors.to_a.join("\n") }}
        format.json { render json: @workflow.errors, status: :internal_server_error }
      end
    end
  end

  # POST /workflows/1/copy
  def copy
    set_workflow

    @workflow = @workflow.copy

    respond_to do |format|
      if @workflow.errors.empty? && @workflow.save
        session[:selected_id] = @workflow.id
        format.html { redirect_to workflows_url, notice: 'Cluster was successfully copied.' }
        format.json { render :show, status: :created, location: @workflow }
      else
        format.html { redirect_to workflows_url, alert: "Cluster failed to be copied: #{@workflow.errors.to_a}" }
        format.json { render json: @workflow.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workflow
      @workflow = Workflow.preload(:jobs).find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def workflow_params
      params.require(:workflow).permit!
    end

    def update_jobs
      # get all of the active workflows
      Workflow.preload(:jobs).active.to_a.each(&:update_status!)
    end
end

apps/clustercomposer/app/helpers/workflows_helper.rb
module WorkflowsHelper
end

apps/clustercomposer/app/views/workflows/_edit_form.html.erb
<%# Uses rails_bootstrap_form gem. API at: https://github.com/bootstrap-ruby/rails-bootstrap-forms %>

<%= bootstrap_form_for(workflow) do |f| %>
    <%= f.alert_message t('clustercomposer.options_errors') %>

    <%= f.text_field :name, label: t('clustercomposer.options_name_title') %>
    <%= f.select :batch_host, OODClusters.map { |cluster| [ "#{cluster.metadata.title}", cluster.id ] }, { selected: @workflow.batch_host, label: t('clustercomposer.options_cluster_title') }, { class: "selectpicker" } %>

    <%# select in bootstrap_form?@%>

    
    <%= f.select :script_path, grouped_options_for_select(workflow.grouped_script_options, workflow.script_path), { label: t('clustercomposer.options_script_title'), help: t('clustercomposer.options_script_help') }, { class: "selectpicker", id: "workflow_script_path" }  %>

    <%= render partial: "edit_form_cluster_attrs", locals: { f: f } %>

    <%= f.submit 'Save', class: 'btn btn-primary' %>
    <%= f.button 'Reset', type: :reset, class: 'btn btn-default' %>

    <%= link_to 'Back', workflows_path, class: 'btn btn-default' %>
<% end %>

apps/clustercomposer/app/views/workflows/_edit_form_cluster_attrs.html.erb
<%# Uses rails_bootstrap_form gem.  i.e.:

  bootstrap_form_for(workflow) do |f|

API at: https://github.com/bootstrap-ruby/rails-bootstrap-forms %>

<%= f.text_field :account,
        label: t('clustercomposer.options_account_title'),
        help: t('clustercomposer.options_account_help') if Configuration.show_cluster_options_account_field?
%>

<% if Workflow.show_cluster_arrays? %>
<%= f.text_field :cluster_array_request,
        label: t('clustercomposer.options_array_title'),
        help: Workflow.not_all_clusters_support_cluster_arrays ?
                  t('clustercomposer.options_array_help_with_clusters',
                      cluster_list: Workflow.clusters_not_supporting_cluster_arrays.join(', '))
                  :
                  t('clustercomposer.options_array_help'),
        placeholder: '1-10'
%>
<% end %>

apps/clustercomposer/app/views/workflows/_form.html.erb
<%# Uses rails_bootstrap_form gem. API at: https://github.com/bootstrap-ruby/rails-bootstrap-forms %>
<%= bootstrap_form_for(workflow) do |f| %>
  <%= f.alert_message "Please fix the errors below." %>

  <div class="form-group">
    <label class="control-label">Template:</label>
    <select class="form-control selectpicker" id="new_job_template_selectpicker">
      <option disabled selected value> -- select a template -- </option>
      <% @templates.each do |template| %>
          <option value="<%= template.to_json %>"><%= template.name %> -- <%= template.notes || template.path %></option>
      <% end %>
    </select>
  </div>

  <%= f.text_field :name, required: true, id: 'name_field' %>

  <%= f.select :batch_host, OODClusters.map { |cluster| [ "#{cluster.metadata.title}", cluster.id ] }, { label: "Cluster:" }, { class: "selectpicker", id: "batch_host_select", required: true } %>
  <%= f.text_field :script_path, required: true, id: "script_path_field" %>

  <%= f.submit 'Save', class: 'btn btn-primary' %>
  <%= f.button 'Reset', type: :reset, class: 'btn btn-default' %>

  <%= link_to 'Back', workflows_path, class: 'btn btn-default' %>
  <%= link_to 'Show', workflow, class: 'btn btn-primary' unless workflow.new_record? %>

  <%= link_to '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Template'.html_safe, new_template_path, { class: 'btn btn-default pull-right', title: "Create a new template", 'data-toggle': 'tooltip', role: 'button' } %>
<% end %>

apps/clustercomposer/app/views/workflows/_new_from_path_form.html.erb
<%# Uses rails_bootstrap_form gem. API at: https://github.com/bootstrap-ruby/rails-bootstrap-forms %>

<%= bootstrap_form_for(workflow, url: create_from_path_path) do |f| %>
    <%= f.alert_message "Please fix the errors below." %>

    <div class="panel panel-default">
      <div class="panel-heading">
        Path to source <strong>(Required)</strong>
      </div>
      <div class="panel-body">
        <%= f.text_field :staging_template_dir, label: "Source path", required: true, help: "Enter the path to a directory on the file system. The contents of this path will be copied to a new workflow." %>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        Job Attributes <strong>(Optional)</strong>
      </div>
      <div class="panel-body">
        <%= f.text_field :name %>

        <%= f.text_field :script_name %>

        <%= f.select :batch_host, OODClusters.map { |cluster| [ "#{cluster.metadata.title}", cluster.id ] }, { label: "Cluster:", :include_blank => true }, { class: "selectpicker", id: "batch_host_select" } %>

        <%= f.text_field :account, help: "Account is an optional field. If not set, the account may be auto-set by the submit filter." %>
      </div>
    </div>

    <%= f.submit 'Save', class: 'btn btn-primary' %>
    <%= f.button 'Reset', type: :reset, class: 'btn btn-default' %>

    <%# <%= link_to 'Back', workflows_path, class: 'btn btn-default' %>
<% end %>

apps/clustercomposer/app/views/workflows/edit.html.erb
<div class="container">
  <div class="page-header">
    <h3><%= t('clustercomposer.options_title') %></h3>
  </div>

  <%= render 'edit_form', workflow: @workflow %>

</div>

apps/clustercomposer/app/views/workflows/index.html.erb
<div class="page-header" xmlns="http://www.w3.org/1999/html">
  <h2>Cluster Composer</h2>
</div>

<% if OODClusters.any? %>
  <div class="row">

    <div class="col-md-7">
      <div cladd="panel panel-thin">
        <div class="panel-body">
          <div class="btn-group open">
            <button type="button" id="new_job_button" class="btn btn-info btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Cluster <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
              <% if @default_template.exist? %>
              <li><a data-method="post" data-toggle="tooltip" title="Create a new cluster from the default template" href="<%= create_default_path %>">From Default Template</a></li>
              <% end %>
              <% if @templates.any? %>
              <li><a href="<%= new_workflow_path %>" data-toggle="tooltip" title="Create a new cluster from a template you choose">From Template</a></li>
              <% end %>
              <li><a href="<%= new_from_path_path %>">From Specified Path/URL</a></li>
              <li role="separator" class="divider"></li>
              <li><a id="copy_button" data-toggle="tooltip" title="Copy the selected cluster" data-method="post" disabled>From Selected Template/Cluster</a></li>
            </ul>
          </div>

          <a class="pull-right btn btn-default btn-sm btn-templates" id="template_button" data-toggle="tooltip" title="Create template from selected cluster" data-method="get" role="button" disabled>
            <span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span><span class="hidden-xs hidden-md"> Create Template</span>
          </a>
        </div>
      </div>
    </div>
  </div>
<% end %>


<div class="row">
  <div class="col-md-7" id="joyride_start">
    <div id="job-list-view" class="panel panel-default">
      <div class="panel-body">
        <a class="btn btn-default btn-sm btn-primary" id="open_dir_button" target="_blank" data-toggle="tooltip" title="Open Directory in File Manager" role="button" disabled>
          <span class="glyphicon glyphicon-edit" aria-hidden="true"></span><span class="hidden-xs"> Edit Files</span>
        </a>
        <!-- <a class="btn btn-default btn-sm" id="view_button" data-toggle="tooltip" title="View Job" role="button" data-method="get" disabled><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a> -->
        <a class="btn btn-default btn-sm btn-primary" id="edit_button" data-toggle="tooltip" title="Change Cluster Configuration" role="button" data-method="get" disabled>
          <span class="glyphicon glyphicon-cog" aria-hidden="true"></span><span class="hidden-xs">  Cluster Options</span>
        </a>
        <a class="btn btn-default btn-sm btn-primary" id="terminal_button" target="_blank" data-toggle="tooltip" title="Open Selected Job in the Terminal" role="button" disabled>
          <span class="glyphicon glyphicon-console" aria-hidden="true"></span><span class="hidden-xs"> Open Terminal</span>
        </a>
        <a class="btn btn-success btn-sm" id="submit_button" data-toggle="tooltip" title="Start Cluster" role="button" data-method="get" disabled>
          <span class="glyphicon glyphicon-play" aria-hidden="true"></span><span class="hidden-xs hidden-md">  Start</span>
        </a>
        <a class="btn btn-default btn-sm btn-warning" id="stop_button" data-toggle="tooltip" title="Stop Cluster" role="button" data-method="get" disabled>
          <span class="glyphicon glyphicon-stop" aria-hidden="true"></span><span class="hidden-xs hidden-md">  Stop</span>
        </a>
        <a class="btn btn-default btn-sm btn-warning" id="eject_button" data-toggle="tooltip" title="Cleanup Resources" role="button" data-method="get" disabled>
          <span class="glyphicon glyphicon-eject" aria-hidden="true"></span><span class="hidden-xs hidden-md">  Eject</span>
        </a>
        <a class="btn btn-default btn-sm noanimate" id="loading_button" title="Loading Job Information" role="button">
          <span class="glyphicon glyphicon-repeat fast-right-spinner" aria-hidden="true"></span>
          <span class="hidden-xs hidden-md">  Loading</span>
        </a>
        <a class="btn btn-danger btn-sm pull-right" id="destroy_button" data-toggle="tooltip" title="Delete Job" data-method="get" data-confirm="Are you sure?" role="button" disabled>
          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> <span class="hidden-xs hidden-md"> Delete</span>
        </a>
      </div>

<a href="deadend.html">debug</a>
      <div class="panel-body">
        <table id="job-list-table" class="table data-table" style="width:100%; table-layout: fixed;">
          <thead>
          <tr>
            <th>Created</th>
            <th>Name</th>
            <th>Type</th>
            <th>ID</th>
            <th>Cluster</th>
            <th>Status</th>
            <!-- FILE_SIZE_FEATURE
            <th>Size</th>
            -->
          </tr>
          </thead>

          <tbody>
          <% @workflows.each do |workflow| %>
              <tr class="job-row<%= " missing-cluster" unless workflow.batch_host_exists? %><%= " missing-dir" unless workflow.staged_dir_exists? %><%= " missing-script" unless workflow.script_name && workflow.staged_script_exists? %>" id="<%= workflow.id %>">
                <td data-sort="<%= workflow.id %>"><small><%= local_time(workflow.created_at) %></small></td>
                <td><span title="<%= workflow.name %>"><strong><%= workflow.name %></strong></span></td>
                <%# FIXME: AJAX causes a problem with this change %>
                <%# FIXME: Retaining cluster records would be helpful %>
                <td>
                  <% if workflow.xdmod_url_available? %>
                    <%= link_to(workflow.xdmod_url, target: "_blank")  do %>
                      <%= workflow.pbsid %> - <%= content_tag :i, nil, style: "display: inline", class: "fa fa-external-link-square-alt" %>&nbsp;XDMoD
                    <% end %>
                  <% else %>
                    <span title="<%= workflow.pbsid %>"><%= workflow.pbsid %></span>
                  <% end %>
                </td>
                <td><span title="<%= cluster_title workflow.batch_host %>"><%= cluster_title workflow.batch_host %></span></td>
                <td id="status_label_<%= workflow.id %>"><%= status_label(workflow) %></td>
                <!-- FILE_SIZE_FEATURE
                  <td><%# number_to_human_size(Filesystem.new.path_size(workflow.staged_dir)) %></td>
                  -->
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

<a href="deadend.html">debug2</a>
  <div class="col-md-5" id="job-details-container">
<a href="deadend.html">debug3</a>
    <div class="panel panel-default" id="job-details-panel" hidden>
<a href="deadend.html">debug4</a>
      <div class="panel-heading">
        <h3 class="panel-title">Cluster Details</h3>
      </div>
      <div class="panel-body">
        <h4 id="job-details-id"></h4>
        <p>Cluster Name: <h4 class="wrap-line"><strong><span id="job-details-name"></span></strong></h4></p>
        <div id="job-details-submit-to">
          <p>Submit to:</p>
          <input type="text" class="form-control" id="job-details-server" disabled>
          <p class="help-block-submit-to"><i>Cluster is not valid! Edit <a href="#" id="edit-job-options-script-link">Cluster Options</a> to select a valid cluster.</i></p>
        </div>
        <p></p>
      </div>

      <div class="panel-body">
        <div id="script-details-view">
          <p>Script location:</p>
          <pre id="job-details-staged-dir"></pre>
          <p class="help-block-dir"><i>Job Directory is missing!</i></p>
        </div>
        <div id="script-details-name-view">
          <p>Script name:</p>
          <pre id="job-details-script-name" disabled></pre>
          <p class="help-block-script"><i>Script is not valid! Edit <a href="#" id="edit-job-options-link">Cluster Options</a> to select a valid script.</i></p>
        </div>
      </div>

      <div id="job-details-view" class="panel-body folder-content-view">
        <p>Folder Contents:</p>
        <span id="job-details-staged-dir-contents"></span>
      </div>
    </div>

    <div class="panel panel-default" id="script-details-panel" hidden>
      <div class="panel-heading">
        <h3 class="panel-title">Submit Script</h3>
      </div>
      <div id="script-text-panel" class="panel-body">
        <h4 id="script-name"></h4>
        <p>Script contents:</p>
        <pre id="script-text-data"></pre>
        <p>
          <a class="btn btn-info btn-sm" style="margin: 5px" id="open-editor-button" target="_blank" data-toggle="tooltip" title="Open Directory in File Editor" role="button"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Open Editor</a>
          <a class="btn btn-primary btn-sm pull-right" style="margin: 5px" id="open-script-dir-button" target="_blank" data-toggle="tooltip" title="Open Directory in File Manager" role="button"><span class="glyphicon glyphicon-new-window" aria-hidden="true"></span> Open Dir</a>
          <a class="btn btn-default btn-sm pull-right" style="margin: 5px" id="open-terminal-dir-button" target="_blank" data-toggle="tooltip" title="Open Directory in Terminal" role="button"><span class="glyphicon glyphicon-console" aria-hidden="true"></span> Open Terminal</a>
        </p>
      </div>
    </div>
  </div>

  <!-- Joyride steps -->
  <ol id="joyride" style="display: none;" data-joyride>
    <li data-id="new_job_button">
      <ol>
        <h4>
          Steps to create a cluster:
        </h4>
        <li>
          <b>Create</b> a new cluster by copying from an existing cluster template directory or a previously run cluster directory.
        </li>
        <li>
          <b>Edit</b> the files in the cluster via the file explorer.
        </li>
        <li>
          <b>Create</b> the cluster and monitor the progress from the "Cluster Composer" index page.
        </li>
      </ol>
    </li>
    <li data-id="new_job_button">
      <p>
      1. Create: Begin by creating a new cluster from an existing template,
      from any arbitrary path on the file system, or by copying a cluster you have
      already created through the Cluster Composer.
      </p>
    </li>
    <li data-id="open_dir_button">
      <p>
        2. Edit: Select a cluster and click here to open the path in the file explorer so you can edit the cluster's files.
      </p>
    </li>
    <li data-id="edit_button">
      <p>
        2. Edit: Select an existing cluster and click here to specify the cluster's server and submit script.
      </p>
    </li>
    <li data-id="terminal_button">
      <p>
        2. Edit: Select an existing cluster and click here to open a new terminal to the cluster path.
      </p>
    </li>
    <li data-id="submit_button">
      <p>
        3. Submit: Select an existing cluster and click here to submit the cluster to the batch queue.
      </p>
    </li>
    <li data-id="stop_button">
      <p>
        Select a running or queued cluster and click here to stop the cluster.
      </p>
    </li>
    <li data-id="destroy_button">
      <p>
        Select an existing cluster and click here to remove the cluster from the list.
      </p>
    </li>
    <li data-id="template_button" data-button="Close">
      <p>
        You can also create new cluster templates from existing clusters. This way, you can use that cluster as a template for future clusters. Select the cluster in the table to copy, then click "Create Template" to initiate the template creation process.
      </p>
    </li>
  </ol>
</div>

apps/clustercomposer/app/views/workflows/new_from_path.html.erb
<div class="container">
  <div class="page-header">
    <h3>Create a new cluster from a path</h3>
  </div>

  <%= render 'new_from_path_form', workflow: @workflow %>
</div>

apps/clustercomposer/app/views/workflows/show.html.erb
<div class="container">
  <div class="page-header">
    <h3>Showing Job</h3>
  </div>

  <p>
    <strong>Name:</strong>
    <%= @workflow.name %>
  </p>

  <p>
    <strong>Batch host:</strong>
    <%= @workflow.batch_host %>
  </p>

  <p>
    <strong>Staged Dir:</strong>
    <%= link_to(@workflow.staged_dir, Filesystem.new.fs(@workflow.staged_dir), target: "_blank") %>
  </p>

  <p>
    <strong>Directory Contents:</strong>
  <ul>
    <% @workflow.folder_contents.each do |content| %>
        <li><%= content.path %></li>
    <% end %>
  </ul>
  </p>

  <%= link_to 'Back', workflows_path, class: 'btn btn-default' %>
  <%= link_to 'Edit', edit_workflow_path(@workflow), class: 'btn btn-default' %>
</div>